name: pylint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - run: pip install pylint
      # Show results but never fail:
      - run: pylint $(git ls-files '*.py') --exit-zero
